name: Docker
on:
  push:
    tags: ["v*"]
  pull_request:
  release:
    types: [published, released]

jobs:
  multi:
    name: "Multi"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Check Docker Hub Credentials
        id: check_dockerhub_credentials
        if: github.event_name == 'release' || github.event_name == 'push'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          if [ "${DOCKER_USERNAME}" == "" ]; then
            echo "Missing Username"
            echo "##[set-output name=missingsecrets;]$(echo yes)"
          elif [ "${DOCKERHUB_TOKEN}" == "" ]; then
            echo "Missing Token"
            echo "##[set-output name=missingsecrets;]$(echo yes)"
          else
            echo "All secrets present"
            echo "##[set-output name=missingsecrets;]$(echo no)"
          fi

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push to Docker Hub
        if: |
          (github.event_name == 'release' || github.event_name == 'push') &&
          contains(steps.check_dockerhub_credentials.outputs.missingsecrets, 'no')
        uses: docker/build-push-action@v2
        with:
          push: true
          repository: mrehbr/golang-repo-template
          tag_with_ref: true
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
